package com.github.panatmosphericvoyage.optimizer.lexer;

public enum TokenType {

	IDENTIFIER,
	NUMBER,
	NUMBER_UNIT,
	OPERATOR_EQUALS,
	OPERATOR_ADD,
	OPERATOR_SUBTRACT,
	OPERATOR_MULTIPLY,
	OPERATOR_DIVIDE,
	OPERATOR_EXPONENT,
	OPERATOR_GREATER,
	OPERATOR_GREATER_EQUAL,
	OPERATOR_LESS,
	OPERATOR_LESS_EQUAL,
	OPERATOR_NOT_EQUAL,
	BRACE_OPEN,
	BRACE_CLOSE,
	PARENTHESIS_OPEN,
	PARENTHESIS_CLOSE,
	BRACKET_OPEN,
	BRACKET_CLOSE,
	STATEMENT_SEPARATOR,
	STATEMENT_TERMINATOR,

}
